name: test_vowels

on: 
  push:
    branches:
      - main
jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.11
      uses: actions/setup-python@v4
      with:
        python-version: 3.11
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        pip install pylint pytest-cov pylint-exit

    - name: Analysing the code with pylint
      run: |
        pylint "C:\Users\rofi2\OneDrive\Dokumente\4. Semester\SSP I - Informatik - Objektorientierte Modellierung\Github\Ronjas_Repository\vowels_eingabe" --disable=C0111 || pylint-exit $?
    
    - name: Test the code with pytest
      run: | 
        pytest --cov=test_vowels_eingabe --cov-fail-under=90 --cov-branch "C:\Users\rofi2\OneDrive\Dokumente\4. Semester\SSP I - Informatik - Objektorientierte Modellierung\Github\Ronjas_Repository\vowels_eingabe"
    
